name: pipeline para revisar archivo

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chechout del codigo
        uses: actions/checkout@v4

      - name: Usar Node JS
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Construir app con Node JS
        run: npm install
        
      - name: Revisar si api.js existe 
        run: |
          if [ ! -f "$GITHUB_WORKSPACE/api.js" ]; then
            echo "El archivo api.js No existe."
            exit 1
          fi
          echo "El archivo api.js existe. Continuando con el Workflow."